### ISSUE TITLE
Editorsupport for Development

### ISSUE THREAD

**Issue by Neuxxx** [VulcanTechnologies/HoloLensCameraStream#11]
Hello,

can you add support for the Editor Play mode.
This make it lot easyer to test and evaluate for computer Vision

**Comment by SoylentGraham** [comment]
You could quickly write a wrapper in the component that uses unity's `WebcamTexture` seeing as (I believe) the UWP implementation here requires .net 4.X+ so won't be compatible with unity.

But, I might be wrong here, maybe a [.net 4.x, 64bit] DLL built for windows will still work because unity's c# runtime just uses the interfaces from the DLL? C# and the .net runtimes are still a little bit of new ground to me (coming from c/c++)

@Neuxxx have you tried building the plugin project (not the dummy one) for 64bit and using it in the editor?

**Comment by Neuxxx** [comment]
yes I tried that but it does not work.

**Comment by SoylentGraham** [comment]
Out of curiosity, in what way didn't it work? Would unity not load the DLL, with some specific .net related error?
Or wouldn't compile?
Or it couldn't find a camera?
