### ISSUE TITLE
FrameSampleAcquired not triggered when the camera is turned on

### ISSUE THREAD

**Issue by akilaVis** [VulcanTechnologies/HoloLensCameraStream#16]
Hi, thank you for the plugin! 

I tried it and it works just fine when the camera is not already used, but when I launched another thread for video chat, I couldn’t access to the camera values, the event FrameSampleAcquired is not triggered, do you know how I can fix that?

Thank you for your help

**Comment by motionsmith** [comment]
Sorry for the late response. In case other people have this problem, I think the issue is that the HoloLens only seems to support one handle to the video stream. I get similar problems when trying to run the MR capture alongside any app that accesses the video camera. The reason why this problem exists is beyond my knowledge.
