### ISSUE TITLE
Integration in Unity 2017.2

### ISSUE THREAD

**Issue by Baxab** [VulcanTechnologies/HoloLensCameraStream#26]
Hello,
I am trying to use your tool in Unity 2017.2.0f3. I followed your instructions for building the dlls and modified some bits of code in the examples, since Unity thought that your VideoCapture class was its class in the namespace UnityEngine.XR.WSA.WebCam (https://docs.unity3d.com/2017.2/Documentation/ScriptReference/XR.WSA.WebCam.VideoCapture.html); so I had to change some declarations here and there. Anyway, the unity project compiled and the VideoPanel example scene was built correctly. Then, I deployed it on the HoloLens. The application started, but it immediately crashed. the problem is that Visual Studio doe not detect any error and I only have a simple output message, shown in the attached image. What could be the problem?
![output](https://user-images.githubusercontent.com/30930839/32660705-c30283be-c61b-11e7-8cd6-6ceebcc5587f.jpg)

**Comment by mtee** [comment]
had the same issue. What fixed it for me was to switch to "Release" solution configuration.

Also, I didn't have to change anything in code except of 2 or 3 include statements, where I had to change
UnityEngine.VR.* to UnityEngine.XR.*

**Comment by motionsmith** [comment]
Hey @Baxab, I made the upgrade yesterday. You can get a working version that WILL build in debug mode (and release mode) [from this branch](https://github.com/VulcanTechnologies/HoloLensCameraStream/tree/unity20173upgrade).

The problem was that Unity introduced a bug in the method `UnityEngine.WSA.Application.InvokeOnMainThread()`. You can see from the changelog on this new branch that I swapped that function out with my own version of this function, so now it should work.

Warning: There is a problem with the ProjectionMapping sample scene in this branch, where the render quad is positioned too far away from the user. I'm not sure if this problem will affect your use case or not.
