### ISSUE TITLE
VideoCaptureSample.CopyRawImageDataIntoBuffer () returns the byte sequence of the image rotated by 180 degrees.

### ISSUE THREAD

**Issue by EnoxSoftware** [VulcanTechnologies/HoloLensCameraStream#6]
Thank you very much for the wonderful asset.

I am a developer of OpenCV for Unity.
https://www.assetstore.unity3d.com/#!/content/21088

I tested a project that combines HoloLensVideoCaptureExample and OpenCVforUnity ,and it works fine.　FPS has improved compared to using WebCamTexture.
However, since the byte sequence by CopyRawImageDataIntoBuffer () is rotated by 180 degrees, it is necessary to rotate again before image processing with OpenCV.

Is there a way to get the byte sequence not rotated by 180 degrees?

**Comment by motionsmith** [comment]
Hey, this is a good question. Thanks for your work on OpenCV for Unity. I'm a happy customer of that product.

Are you saying the image is upside down from what you're expecting, or that it's mirrored?

My understanding, after studying the Media Foundation Pipeline, is that it's the responsibility of the renderer to do mirroring, probably because the GPU can do it very quickly with minimal overhead. This case might be less helpful for passing it to OpenCV.

If the image is upside down, there is a way in the MediaFoundation pipeline to prevent it from being rotated but I'd be curious to understand why your images are upside down and mine aren't. The best solution would be to add this as a setting when you call `StartVideoModeAsync()`.

Here is the [line of code that flips it](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensCameraStream/Plugin%20Project/VideoCapture.cs#L235). We could make some changes to allow it to be set conditionally, but it would be nice to understand why your image is upside down.

Sorry for the slow response. I hope this helps and look forward to hearing back.
Eric

**Comment by EnoxSoftware** [comment]
Thank you very much for purchasing my products.

The reason for the #1  issue is the order of byte sequences required by the Texture2D.LoadRawTextureData() method.
The colors array of [Texture2D.LoadRawTextureData()](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanel.cs#L22) is a flattened 2D array, where pixels are laid out left to right, bottom to top (i.e. row after row). 
https://docs.unity3d.com/ScriptReference/Texture2D.SetPixels32.html

This attached file is a sample code combining HoloLensCameraStream and OpenCVforUnity.
[HoloLensVideoCaptureDetectFaceExample.zip](https://github.com/VulcanTechnologies/HoloLensCameraStream/files/949447/HoloLensVideoCaptureDetectFaceExample.zip)
If I comment out [this line](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensCameraStream/Plugin%20Project/VideoCapture.cs#L235) and use a recompiled your plugin, I can get a byte sequence in the easy to use order.

```
        lock (sync) {
            OpenCVForUnity.Utils.copyToMat<byte> (_latestImageBytes, bgraMat);//copy to OpenCV's Mat.
        }


        Core.flip (bgraMat, bgraMat, -1);//If comment out properties.Properties.Add(ROTATION_KEY, 180);,this line is not necessary.
```

**Comment by motionsmith** [comment]
Thanks for sticking with me on this. You might be right, but I'm confused as to why the example project is working correctly then:

In my provided example App, I [am calling](https://github.com/VulcanTechnologies/HoloLensCameraStream/blob/master/HoloLensVideoCaptureExample/Assets/CamStream/Examples/Video%20Panel%20Example/Scripts/VideoPanel.cs#L22) `LoadRawTextureData()` and the image appears correct-side-up for me. 

In the example Unity project with no edits, is the image upside down for you?

When I was fixing issue #1, I captured an image with all red pixels on top and all white pixels on bottom [like this](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_red_white.svg/2000px-Flag_red_white.svg.png). I viewed the resulting byte array in the debugger and, without that 180 degree rotation, the first pixels were white and I would expect them to be red. Furthermore, when I viewed the example project, the image was upside-down. When I include the 180 degree rotation, `LoadRawTextureData` loads the image correclty, and the bytes properly start with red pixels and and with white pixels.

Am I missing something? Maybe I should just include an option to customize the rotation.

**Comment by EnoxSoftware** [comment]
> In the example Unity project with no edits, is the image upside down for you?

Your provided example is no problem.
In your provided example App with no edits, the image appears correct-side-up.

> Maybe I should just include an option to customize the rotation.

I’d appreciate it if you could add an option to customize the rotation. I think that this change is beneficial for other users as well.

**Comment by motionsmith** [comment]
There is now an option to bypass the 180 degree rotation. Thanks @EnoxSoftware and @SoylentGraham!

**Comment by zyjisdog** [comment]
> 
> 
> There is now an option to bypass the 180 degree rotation. Thanks @EnoxSoftware and @SoylentGraham!

But the capture result is flipped horizontally that left things in the real world appear in the right on the video panel.
