### ISSUE TITLE
Can this plugin work on hololens2 (arm) ?

### ISSUE THREAD

**Issue by pandalee86** [VulcanTechnologies/HoloLensCameraStream#63]

**Comment by brookman** [comment]
I managed to compile the plugin for ARM (64) however some APIs have changed and TryGetCameraToWorldMatrix as well as TryGetProjectionMatrix don't work anymore. Guids go get the matrices are not valid anymore.
I am currently struggling to get it running again.

**Comment by lapislazinus** [comment]
Worked straight out of the box for me (compiled with AnyCPU) but i only tested getting the frame, nothing else

**Comment by brookman** [comment]
Getting the frame works. It is however not possible to convert from image coordinates to world coordinates. So for example you can't run object detection on the frame and then get a world ray of the object (center, bounds).

**Comment by lapislazinus** [comment]
You are right, TryGetCameraToWorldMatrix and TryGetProjectionMatrix don't work anymore.
Tried to find any official info on the Guids but unsuccessful.
Honestly, i don't think i have the expertise to get this running again, but i hope someone does^^
Until then, i guess i have to use the PhotoCapture stuff again...

**Comment by pandalee86** [comment]
It works well on my hololens2 now.
TryGetProjectionMatrix returns a normal matrix. I think it works ok.
But TryGetCameraToWorldMatrix doesn't work. Because worldOrigin is null.

**Comment by nous-** [comment]
Why was this closed when localizing cameras from a live stream was the key value add of this library?

**Comment by EnoxSoftware** [comment]
I'm curious if the issue in Hololens 2 discussed here is related to this issue.
https://issuetracker.unity3d.com/issues/photocaptureframe-provides-wrong-camera-matrices-on-hololens-2

**Comment by EnoxSoftware** [comment]
Could someone try out if this native plugin can work with Hololens2 and replace HololensCameraStream?
https://github.com/carmines/UnityPluginCollection/tree/master/CameraCapture

I haven't been able to check it out as I don't have Hololens2 at hand, but I have confirmed that I can get video preview and camera matrices successfully on Hololens.

**Comment by EnoxSoftware** [comment]
I found a very interesting repository.
https://github.com/qian256/HoloLensARToolKit
This repository seems to include how to get the video preview and camera matrices of the camera on the Hololens2 device I was looking for.
I think it will be very helpful when modifying this plugin to work properly on the hololens2.

**Comment by nous-** [comment]
Hello, I want to do this more formally, but I haven't found the time and wanted to get something out because it seems it would help others. A lot of energy goes into figuring this stuff out so I appreciate the original authors work. We solved this by moving all the first order data out of the libraries into a colab so we could slowly walk the matrix math and figure out what was going on.

To get this working on H2:

In `VideoCaptureSample.cs` in the Plugin folder, this is the code you'll need to get to world coordinates on Hololens 2. This is in right handed coordinates. You'll want to flip this to left-handed coordinates for Unity, or update this code below to have it match the original version (recommended). We don't have any conditionals to run the H1 logic.

```cs
public bool TryGetCameraToWorldMatrix(out float[] outMatrix)
{
  if (worldOrigin == null)
  {
    outMatrix = GetIdentityMatrixFloatArray();
    return false;
  }

  var cameraToWorldFrame = frameReference.CoordinateSystem.TryGetTransformTo(worldOrigin);
  if (!cameraToWorldFrame.HasValue)
  {
    outMatrix = GetIdentityMatrixFloatArray();
    return false;
  }

  outMatrix = ConvertMatrixToFloatArray(cameraToWorldFrame.Value);
  return true;
}
```

To move from right to left handed coordates in Unity:

```cs
private static Matrix4x4 invZ = Matrix4x4.TRS(Vector3.zero, Quaternion.identity, new Vector3(1, 1, -1));
Matrix4x4 conv(Matrix4x4 matrix) {
  // https://stackoverflow.com/questions/30234945/change-handedness-of-a-row-major-4x4-transformation-matrix
  return invZ * matrix * invZ;
}
```

I also needed to get the Hololens camera intrinsics which was done like this.

```cs
public float[] GetCameraIntrinsics()
{
  var i = frameReference.VideoMediaFrame.CameraIntrinsics;
  return new float[] {
    i.ImageWidth, i.ImageHeight,
    i.FocalLength.X, i.FocalLength.Y,
    i.PrincipalPoint.X, i.PrincipalPoint.Y,
    i.RadialDistortion.X, i.RadialDistortion.Y, i.RadialDistortion.Z,
    i.TangentialDistortion.X, i.TangentialDistortion.Y
  };
}
```

Unpacked in Unity with (Vector2Int comes from OpenCV for Unity):

```cs
public class CameraIntrinsics {
  public Vector2Int resolution;
  public Vector2 focalLength;
  public Vector2 principalPoint;
  public Vector3 radialDistortion;
  public Vector2 tangentialDistortion;

  public static CameraIntrinsics from(float[] v) {
    return new CameraIntrinsics() {
      resolution = new Vector2Int((int)v[0], (int)v[1]),
      focalLength = new Vector2(v[2], v[3]),
      principalPoint = new Vector2(v[4], v[5]),
      radialDistortion = new Vector3(v[6], v[7], v[8]),
      tangentialDistortion = new Vector2(v[9], v[10])
    };
  }
}
```

The world coordinate system established somewhere in Unity needs to be passed to the library to move camera space to unity world space. I believe I was seeing null come out of this first version, but found this second version worked. This was with MRTK 2.5 (but I believe I also had this running with 2.4 -- may not be relevant).

```cs
// Hololens 1
// _spatialCoordinateSystemPtr = UnityEngine.XR.WSA.WorldManager.GetNativeISpatialCoordinateSystemPtr();

// Hololens 2
_spatialCoordinateSystemPtr = Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityUtilities.UtilitiesProvider.ISpatialCoordinateSystemPtr;
```

Ping if there is something you need clarity around.
